setup-environment: detect sourcing in a more robust way
JIRA: EIS-209

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/setup-environment b/setup-environment
--- a/setup-environment
+++ b/setup-environment
@@ -1,6 +1,21 @@
-if [ -z "$ZSH_NAME" ] && [ "x$0" = "x./setup-environment" ]; then
-    echo >&2 "Error: This script needs to be sourced. Please run as '. ./setup-environment'"
+mel_sourced=0
+if [ -n "$ZSH_EVAL_CONTEXT" ]; then 
+    case $ZSH_EVAL_CONTEXT in *:file) mel_sourced=1;; esac
+elif [ -n "$KSH_VERSION" ]; then
+    # shellcheck disable=SC2296
+    [ "$(cd "$(dirname -- "$0")" && pwd -P)/$(basename -- "$0")" != "$(cd "$(dirname -- "${.sh.file}")" && pwd -P)/$(basename -- "${.sh.file}")" ] && mel_sourced=1
+elif [ -n "$BASH_VERSION" ]; then
+    (return 0 2>/dev/null) && mel_sourced=1 
 else
+    echo >&2 "Error: This shell is unsupported. Please use bash, ksh, or zsh"
+    false
+fi
+
+if [ "$mel_sourced" -eq 0 ]; then
+    echo >&2 "Error: This script needs to be sourced. Please run as '. \"$0\"'"
+    false
+else
+    # shellcheck disable=SC2128
     if [ -n "$BASH_SOURCE" ]; then
         layerdir="$(cd "$(dirname "$BASH_SOURCE")" && pwd -P)"
     elif [ -n "$ZSH_NAME" ]; then
