capdebuginfo: updates from PR review
Signed-off-by: arshadaleem66 <arshad_aleem@mentor.com>

diff --git a/scripts/capdebuginfo b/scripts/capdebuginfo
--- a/scripts/capdebuginfo
+++ b/scripts/capdebuginfo
@@ -16,7 +16,6 @@
 unset BUILDERR   # Path and filename of the MEL build error log file
 unset MELDIR     # Root path of the MEL installation directory
 
-WORKDIR=${PWD}
 HOMEDIR=${HOME}
 HOSTINFOFILE="hostinfo.txt"    # File containing info captured from user's host
 OUTPUTDIRNAME="capdebuginfo"   # Directory containing all info captured by script
@@ -49,13 +48,6 @@ END
 
 abspath () {
     readlink -e "${1}"
-}
-setup_environment() {
-if("Ubuntu"=`lsb_release -i -s`) then
-   source "${MELDIR}"/meta-mentor/scripts/setup-ubuntu
-else
-   source "${MELDIR}"/meta-mentor/scripts/setup-rh
-fi
 }
 
 # Process input arguments to the script
@@ -94,17 +86,17 @@ process_cmdline_args () {
 get_hostinfo () {
    local __output="${1}/host/${2}"
    
-   echo -en "\nHost Distro Info:\n" >> ${__output}
+   echo -en "\\nHost Distro Info:\\n" >> "${__output}"
    lsb_release -a >> "${__output}" 2> /dev/null
-   echo -en "\nHost System Info:\n" >> "${__output}"
+   echo -en "\\nHost System Info:\\n" >> "${__output}"
    uname -a >> "${__output}"
-   echo -en "\nHost env Info:\n" >> "${__output}"
+   echo -en "\\nHost env Info:\\n" >> "${__output}"
    printenv | sort >> "${__output}"
-   echo -en "\nHost disk space usage:\n" >> "${__output}"
+   echo -en "\\nHost disk space usage:\\n" >> "${__output}"
    df -h >> "${__output}"
-   echo -en "\nHost memory usage:\n" >> "${__output}"
+   echo -en "\\nHost memory usage:\\n" >> "${__output}"
    free -ht >> "${__output}"
-   echo -en "\n" >> "${__output}"
+   echo -en "\\n" >> "${__output}"
 }
 
 
@@ -114,30 +106,30 @@ get_hostinfo () {
 #           $3=License info variable name
 get_hostlicenseinfo () {
    local __outputdir="${1}"
-   local __output="${1}/host/${2}"
+   local __output=""${1}"/host/"${2}""
    local __licensename="${3}"
-   local __license=`printenv "${3}"`
+   local __license=$(printenv "${3}")
 
-   echo -en "\n${__licensename}:\n" >> ${__output}
+   echo -en "\\n\"${__licensename}\":\\n" >> "${__output}"
    # Check if license variable is set in shell environment
    if [ -n "${__license}" ]; then
-      echo -en "${__license}\n" >> "${__output}"
+      echo -en "\"${__license}\"\\n" >> "${__output}"
       # Process license variable string
-      for i in $(echo "${__license//:/$'\n'}"); do
+      for i in $(echo "${__license//:/$'\\n'}"); do
          # Check if entry is a license file and exists
          if [ -f "${i}" ]; then
             # Make a copy of the license file
-            cp "${i}" "${__outputdir}/host/."
+            cp "${i}" "${__outputdir}"/host/.
          # Check if entry is a license server
          elif [[ "${i}" == *"@"* ]]; then
-            echo -en "\n${i} is a license server\n" >> ${__output}
+            echo -en "\\n\"${i}\" is a license server\\n" >> "${__output}"
          # Entry is invalid
          else
-            echo -en "\n${i} does not seem to be a valid entry\n" >> "${__output}"
+            echo -en "\\n\"${i}\" does not seem to be a valid entry\\n" >> "${__output}"
          fi
       done
    else
-      echo -en "\n${__licensename} is not set!\n" >> "${__output}"
+      echo -en "\\n\"${__licensename}\" is not set!\\n" >> "${__output}"
    fi
 }
 
@@ -147,22 +139,30 @@ get_hostlicenseinfo () {
 #           $2=Filename for host info collection
 get_hostprereqsinfo () {
    local __outputdir="${1}"
-   local __output="${1}/host/${2}"
-   local __hostos_distid=`lsb_release -i -s`
-   local __hostos_distvers=`lsb_release -r -s`
+   local __output="${1}"/host/"${2}"
+   local __hostos_distid="$(lsb_release -i -s)"
+   local __hostos_distvers="$(lsb_release -r -s)"
    local __pkgs
    
-   echo -en "\nHost OS is ${__hostos_distid} ${__hostos_distvers}:\n" >> ${__output}
+   echo -en "\\nHost OS is "${__hostos_distid}" "${__hostos_distvers}":\\n" >> "${__output}"
    case "${__hostos_distid}" in
       Ubuntu)
-	 source "${MELDIR}"/meta-mentor/scripts/setup-ubuntu
-         __pkgs="$PKGS"
-         dpkg-query -W -f='${binary:Package} ${Version} ${db:Status-Status}\n' ${__pkgs} >> ${__output}
+         if [ -f "${MELDIR}"/meta-mentor/scripts/setup-ubuntu ]; then
+	    source "${MELDIR}"/meta-mentor/scripts/setup-ubuntu
+            __pkgs="$PKGS"
+            dpkg-query -W -f="${binary:Package}" "${Version}" "${db:Status-Status}"\\n "${__pkgs}" >> "${__output}"
+         else   
+            echo "FATAL: setup-ubuntu script not available at meta-mentor/scripts/"
+         fi
          ;;      
       CentOS|RedHat*)
-         source "${MELDIR}"/meta-mentor/scripts/setup-rh
-         __pkgs="$packages"
-         rpm -q ${__pkgs} >> ${__output}
+         if [ -f "${MELDIR}"/meta-mentor/scripts/setup-rh ]; then
+            source "${MELDIR}"/meta-mentor/scripts/setup-rh
+            __pkgs="$packages"
+            rpm -q "${__pkgs}" >> "${__output}"
+         else
+            echo "FATAL: setup-rh script not available at meta-mentor/scripts/"
+         fi
          ;;
    esac
 }
@@ -175,10 +175,10 @@ get_melinstallinfo () {
    local __outputdir="${1}"
    local __output="${1}/host/${2}"
    
-   if [ -d "${HOMEDIR}/.mentor" ]; then
-      cp -a ${HOMEDIR}/.mentor/.registry ${__outputdir}/host/mentor-registry
+   if [ -d "${HOMEDIR}"/.mentor ]; then
+      cp -a "${HOMEDIR}"/.mentor/.registry "${__outputdir}"/host/mentor-registry
    else
-      echo -en "\nNo MEL install info found!\n" >> ${__output}
+      echo -en "\\nNo MEL install info found!\\n" >> ${__output}
    fi
 }
 
@@ -192,16 +192,16 @@ get_melbuildinfo () {
    local __builderr="${2}"
    local __builddir="${3}"
    
-   local __arch="$(echo ${__builderr#/*/work/} | cut -d"/" -f1)"
-   local __pkgname="$(echo ${__builderr#/*/work/} | cut -d"/" -f2)"
-   local __pkgdir="${__builddir}/tmp/work/${__arch}/${__pkgname}"
+   local __arch="$(echo "${__builderr#/*/work/}" | cut -d"/" -f1)"
+   local __pkgname="$(echo "${__builderr#/*/work/}" | cut -d"/" -f2)"
+   local __pkgdir="${__builddir}"/tmp/work/"${__arch}"/"${__pkgname}"
 
-   cp -a ${__builddir}/buildhistory/images/ ${__outputdir}/mel/.
-   cp -a ${__builddir}/tmp/log/ ${__outputdir}/mel/.
-   cp -a ${__builddir}/conf/ ${__outputdir}/mel/.
+   cp -a "${__builddir}"/buildhistory/images/ "${__outputdir}"/mel/.
+   cp -a "${__builddir}"/tmp/log/ "${__outputdir}"/mel/.
+   cp -a "${__builddir}"/conf/ "${__outputdir}"/mel/.
 
-   mkdir ${__outputdir}/mel/${__arch}
-   cp -a ${__pkgdir} ${__outputdir}/mel/${__arch}/.
+   mkdir "${__outputdir}"/mel/"${__arch}"
+   cp -a "${__pkgdir}" "${__outputdir}"/mel/"${__arch}"/.
 }
 
 
@@ -209,86 +209,84 @@ get_melbuildinfo () {
 #
 # Start execution of script
 #
-#set -x
 
 # Check if the build environment is set or not.
 if [ ! -d "${BUILDDIR}" ]; then
     echo "Please setup the build environment first, and run the script again."
     exit 1
 else
-# Check 1st cmdline argument
-if [[ ${1} == -* ]]; then
-   # Process script input arguments 
-   process_cmdline_args "${@}"
-   
-   if [ ! -d "${BUILDERR}" ]; then
-      echo -en "\nERROR:  Input argument was invalid!!!\n\n"
-   fi
-elif [ -z "${@}" ]; then
-   echo -en "\nWARNING:  No input argument was given on command line.\n\n"
-fi
+	# Check 1st cmdline argument
+	if [[ "${1}" == -* ]]; then
+		# Process script input arguments 
+		process_cmdline_args "${@}"
+		
+		if [ ! -d "${BUILDERR}" ]; then
+		   echo -en "\\nERROR:  Input argument was invalid!!!\\n\\n"
+		fi
+	elif [ -z "${@}" ]; then
+		echo -en "\\nWARNING:  No input argument was given on command line.\\n\\n"
+	fi
 
-# Check for valid BUILDERR
-while [ ! -d "${BUILDERR}" ]; do
-   echo "Please enter package name in which you are having error (option -e):"
-   read IN1
-   BUILDERR="$(find ${BUILDDIR}/tmp/work/ -maxdepth 2 -type d -name "${IN1}")"
-               
-   if [ ! -d "${BUILDERR}" ]; then
-      echo -en "\nERROR (option -e):  Invalid package name!!!\n\n"
-   fi
-done
+	# Check for valid BUILDERR
+	while [ ! -d "${BUILDERR}" ]; do
+		echo "Please enter package name in which you are having error (option -e):"
+		read IN1
+        echo "$IN1"
+		BUILDERR=$(find "${BUILDDIR}/tmp/work/" -maxdepth 2 -type d -name "${IN1}")
+		           echo "$BUILDERR" 
+		if [ ! -d "${BUILDERR}" ]; then
+		   echo -en "\\nERROR (option -e):  Invalid package name!!!\\n\\n"
+		fi
+	done
 
-for i in $(echo $PATH | tr ":" "\n")
-do
-    a="$(echo $i | grep "/bitbake/bin")"
-    if [ -n "$a" ]
-    then
-      break
-    fi
-done
+	for i in $(echo "$PATH" | tr ":" "\\n")
+	do
+		 a="$(echo "$i" | grep "/bitbake/bin")"
+		 if [ -n "$a" ]
+		 then
+		   break
+		 fi
+	done
 
-MELDIR="${a%%/bitbake/bin}"
+	MELDIR="${a%%/bitbake/bin}"
 
+	# Clean up artifacts from previous run of the script
+	if [ -d "${OUTPUTDIRNAME}" ]; then
+		rm -rf "${OUTPUTDIRNAME}"
+	fi
 
+	if [ -a "${OUTPUTDIRNAME}".tar.bz2 ]; then
+		rm "${OUTPUTDIRNAME}".tar.bz2
+	fi
 
-# Clean up artifacts from previous run of the script
-if [ -d "${OUTPUTDIRNAME}" ]; then
-   rm -rf ${OUTPUTDIRNAME}
-fi
+	# Create directories for saving script outputs
+	mkdir -p "${OUTPUTDIRNAME}"/host "${OUTPUTDIRNAME}"/mel
 
-if [ -a "${OUTPUTDIRNAME}.tar.bz2" ]; then
-   rm ${OUTPUTDIRNAME}.tar.bz2
-fi
+	# Collect host information
+	get_hostinfo "${OUTPUTDIRNAME}" "${HOSTINFOFILE}"
+	get_hostlicenseinfo "${OUTPUTDIRNAME}" "${HOSTINFOFILE}" "${MGLS_LICENSE}"
+	get_hostlicenseinfo "${OUTPUTDIRNAME}" "${HOSTINFOFILE} ${LM_LICENSE}"
+	get_hostprereqsinfo "${OUTPUTDIRNAME}" "${HOSTINFOFILE}"
+	get_melinstallinfo "${OUTPUTDIRNAME}" "${HOSTINFOFILE}"
+	get_melbuildinfo "${OUTPUTDIRNAME}" "${BUILDERR}" "${BUILDDIR}"
 
-# Create directories for saving script outputs
-mkdir -p ${OUTPUTDIRNAME}/host ${OUTPUTDIRNAME}/mel
+	# Create tarball with info collected in output directory
+	echo "Creating \"${OUTPUTDIRNAME}\".tar.bz2..."
+	tar cjpf "${OUTPUTDIRNAME}".tar.bz2 "${OUTPUTDIRNAME}" 2>> "${OUTPUTDIRNAME}"/host/"${HOSTINFOFILE}"
 
-# Collect host information
-get_hostinfo ${OUTPUTDIRNAME} ${HOSTINFOFILE}
-get_hostlicenseinfo ${OUTPUTDIRNAME} ${HOSTINFOFILE} ${MGLS_LICENSE}
-get_hostlicenseinfo ${OUTPUTDIRNAME} ${HOSTINFOFILE} ${LM_LICENSE}
-get_hostprereqsinfo ${OUTPUTDIRNAME} ${HOSTINFOFILE}
-get_melinstallinfo ${OUTPUTDIRNAME} ${HOSTINFOFILE}
-get_melbuildinfo ${OUTPUTDIRNAME} ${BUILDERR} ${BUILDDIR}
-
-# Create tarball with info collected in output directory
-echo "Creating ${OUTPUTDIRNAME}.tar.bz2..."
-tar cjpf ${OUTPUTDIRNAME}.tar.bz2 ${OUTPUTDIRNAME} 2>> ${OUTPUTDIRNAME}/host/${HOSTINFOFILE}
-
-# Need to check exit status of tar and handle appropriately
-if [[ ${?} -ne 0 ]]; then
-   echo -en "\ntar errno: ${?}\n" >> ${OUTPUTDIRNAME}/host/${HOSTINFOFILE}
-   cp ${OUTPUTDIRNAME}/host/${HOSTINFOFILE} .
-   echo "An error occurred during tar."
-   echo "Please attach ${HOSTINFOFILE} to your Support Request ticket."
-   exit 1
-else
-   # Remove output directory after creating tarball archive file
-   if [ -d "${OUTPUTDIRNAME}" ]; then
-      rm -rf ${OUTPUTDIRNAME}
-   fi
-   echo "Done!!!"
-   echo -en "\nPlease attach ${OUTPUTDIRNAME}.tar.bz2 to your Support Request ticket.\n\n"
-fi
+	# Need to check exit status of tar and handle appropriately
+	if [[ ${?} -ne 0 ]]; then
+		echo -en "\\ntar errno: ${?}\\n" >> "${OUTPUTDIRNAME}"/host/"${HOSTINFOFILE}"
+		cp "${OUTPUTDIRNAME}"/host/"${HOSTINFOFILE}" .
+		echo "An error occurred during tar."
+		echo "Please attach "${HOSTINFOFILE}" to your Support Request ticket."
+		exit 1
+	else
+		# Remove output directory after creating tarball archive file
+		if [ -d "${OUTPUTDIRNAME}" ]; then
+		   rm -rf "${OUTPUTDIRNAME}"
+		fi
+		echo "Done!!!"
+		echo -en "\\nPlease attach "${OUTPUTDIRNAME}".tar.bz2 to your Support Request ticket.\\n\\n"
+	fi
 fi
