capdebuginfo: Reduced input arguments from 2 to 1
Signed-off-by: Aleem Arshad <arshad_aleem@mentor.com>

diff --git a/scripts/capdebuginfo b/scripts/capdebuginfo
--- a/scripts/capdebuginfo
+++ b/scripts/capdebuginfo
@@ -12,9 +12,7 @@
 # version 2.  This program  is licensed "as is" without any warranty of any
 # kind, whether express or implied.
 
-
 # Variables
-unset BUILDDIR   # Path of the MEL build directory
 unset BUILDERR   # Path and filename of the MEL build error log file
 unset MELDIR     # Root path of the MEL installation directory
 
@@ -32,18 +30,18 @@ usage () {
 
 Description:
    Capture debug info from a MEL user's host such as host environment and project log files.
-   
+   The Script runs only if environment of the shell is already set using setup-environment script.
+
 Modes of operation:
-   With input arguments: ${SCRIPT_NAME} -e <BUILDERR> -i <MELDIR>
+   With input arguments: ${SCRIPT_NAME} -e <PN>
      
    Without input arguments: ${SCRIPT_NAME}
    
-Usage: ${SCRIPT_NAME} -e <BUILDERR> -i <MELDIR>
+Usage: ${SCRIPT_NAME} -e <PN>
    or  ${SCRIPT_NAME}
    
-   -e <BUILDERR>   Specify complete path and filename of the MEL build error log file
-   -i <MELDIR>     Specify the root path of the MEL installation directory 
-   -h              Show this usage information
+   -e <PN>   Specify the name of package causing build failure
+   -h        Show this usage information
 
 END
 }
@@ -52,38 +50,34 @@ END
 abspath () {
     readlink -e "${1}"
 }
-
+setup_environment() {
+if("Ubuntu"=`lsb_release -i -s`) then
+   source "${MELDIR}"/meta-mentor/scripts/setup-ubuntu
+else
+   source "${MELDIR}"/meta-mentor/scripts/setup-rh
+fi
+}
 
 # Process input arguments to the script
 #   Input:  $@
 process_cmdline_args () {
-   while getopts ":e:i:h" opt; do
+   while getopts ":e:h" opt; do
       case "${opt}" in
          e)
             # Handle getops with invalid input
-            if [[ ${OPTARG} == -* ]] ; then
-               echo "Invalid input for option -${opt}"
+            if [[ "${OPTARG}" == -* ]] ; then
+               echo "Invalid input for option -"${opt}""
                shift $((OPTIND-1))
                break
             else
-               BUILDERR="$(abspath ${OPTARG})"
-            fi
-            ;;
-         i)
-            # Handle getops with invalid input
-            if [[ ${OPTARG} == -* ]] ; then
-               echo "Invalid input for option -${opt}"
-               shift $((OPTIND-1))
-               break
-            else
-               MELDIR="$(abspath ${OPTARG})"
+               BUILDERR=$(find "${BUILDDIR}/tmp/work/" -maxdepth 2 -type d -name "${OPTARG}")
             fi
             ;;
          :)
-            echo "Option -${OPTARG} requires an argument." >&2
+            echo "Option -"${OPTARG}" requires an argument." >&2
             ;;
          \?)
-            echo "Invalid option: -${OPTARG}" >&2
+            echo "Invalid option: -"${OPTARG}"" >&2
             ;;
          h)
             usage
@@ -101,16 +95,16 @@ get_hostinfo () {
    local __output="${1}/host/${2}"
    
    echo -en "\nHost Distro Info:\n" >> ${__output}
-   lsb_release -a >> ${__output} 2> /dev/null
-   echo -en "\nHost System Info:\n" >> ${__output}
-   uname -a >> ${__output}
-   echo -en "\nHost env Info:\n" >> ${__output}
-   printenv | sort >> ${__output}
-   echo -en "\nHost disk space usage:\n" >> ${__output}
-   df -h >> ${__output}
-   echo -en "\nHost memory usage:\n" >> ${__output}
-   free -ht >> ${__output}
-   echo -en "\n" >> ${__output}
+   lsb_release -a >> "${__output}" 2> /dev/null
+   echo -en "\nHost System Info:\n" >> "${__output}"
+   uname -a >> "${__output}"
+   echo -en "\nHost env Info:\n" >> "${__output}"
+   printenv | sort >> "${__output}"
+   echo -en "\nHost disk space usage:\n" >> "${__output}"
+   df -h >> "${__output}"
+   echo -en "\nHost memory usage:\n" >> "${__output}"
+   free -ht >> "${__output}"
+   echo -en "\n" >> "${__output}"
 }
 
 
@@ -127,23 +121,23 @@ get_hostlicenseinfo () {
    echo -en "\n${__licensename}:\n" >> ${__output}
    # Check if license variable is set in shell environment
    if [ -n "${__license}" ]; then
-      echo -en "${__license}\n" >> ${__output}
+      echo -en "${__license}\n" >> "${__output}"
       # Process license variable string
       for i in $(echo "${__license//:/$'\n'}"); do
          # Check if entry is a license file and exists
          if [ -f "${i}" ]; then
             # Make a copy of the license file
-            cp ${i} ${__outputdir}/host/.
+            cp "${i}" "${__outputdir}/host/."
          # Check if entry is a license server
-         elif [[ ${i} == *"@"* ]]; then
+         elif [[ "${i}" == *"@"* ]]; then
             echo -en "\n${i} is a license server\n" >> ${__output}
          # Entry is invalid
          else
-            echo -en "\n${i} does not seem to be a valid entry\n" >> ${__output}
+            echo -en "\n${i} does not seem to be a valid entry\n" >> "${__output}"
          fi
       done
    else
-      echo -en "\n${__licensename} is not set!\n" >> ${__output}
+      echo -en "\n${__licensename} is not set!\n" >> "${__output}"
    fi
 }
 
@@ -161,17 +155,13 @@ get_hostprereqsinfo () {
    echo -en "\nHost OS is ${__hostos_distid} ${__hostos_distvers}:\n" >> ${__output}
    case "${__hostos_distid}" in
       Ubuntu)
-         __pkgs="bmap-tools bzip2 chrpath cvs diffstat gawk gcc git-core gzip g++ \
-                 libgl1-mesa-dev libglu1-mesa-dev libncurses5-dev libsdl1.2-dev \
-                 lsb-release make patch python python3 subversion tar texinfo \
-                 texi2html ubuntu-minimal ubuntu-standard zip"
+	 source "${MELDIR}"/meta-mentor/scripts/setup-ubuntu
+         __pkgs="$PKGS"
          dpkg-query -W -f='${binary:Package} ${Version} ${db:Status-Status}\n' ${__pkgs} >> ${__output}
          ;;      
       CentOS|RedHat*)
-         __pkgs="bzip2 chrpath cvs diffstat gawk gcc gcc-c++ git glibc-devel \ 
-                 glibc-static gzip make ncurses-devel patch perl-Thread-Queue \
-                 python python34 python-virtualenv redhat-lsb SDL-devel sqlite \
-                 subversion tar tetex texinfo texi2html wget"
+         source "${MELDIR}"/meta-mentor/scripts/setup-rh
+         __pkgs="$packages"
          rpm -q ${__pkgs} >> ${__output}
          ;;
    esac
@@ -215,7 +205,7 @@ get_melbuildinfo () {
 }
 
 
-
+########################################################################################################
 #
 # Start execution of script
 #
@@ -225,7 +215,7 @@ get_melbuildinfo () {
 if [[ ${1} == -* ]]; then
    # Process script input arguments 
    process_cmdline_args "${@}"
-   if [ ! -f "${BUILDERR}" ] || [ ! -d "${MELDIR}" ]; then
+   if [ ! -d "${BUILDERR}" ]; then
       echo -en "\nERROR:  One or more input arguments were invalid!!!\n\n"
    fi
 elif [ -z "${@}" ]; then
@@ -233,29 +223,18 @@ elif [ -z "${@}" ]; then
 fi
 
 # Check for valid BUILDERR
-while [ ! -f "${BUILDERR}" ]; do
-   echo "Please enter error log filename and complete path displayed from MEL project (option -e):"
-   read BUILDERR
-   BUILDERR="$(abspath ${BUILDERR})"
-   if [ ! -f "${BUILDERR}" ]; then
-      echo -en "\nERROR (option -e):  Invalid error log filename and path!!!\n\n"
+while [ ! -d "${BUILDERR}" ]; do
+   echo "Please enter package name in which you are having error (option -e):"
+   read IN1
+   BUILDERR="$(find ${BUILDDIR}/tmp/work/ -maxdepth 2 -type d -name "${IN1}")"
+               
+   if [ ! -d "${BUILDERR}" ]; then
+      echo -en "\nERROR (option -e):  Invalid package name!!!\n\n"
    fi
 done
 
-# Check for valid MELDIR
-while [ ! -d "${MELDIR}" ]; do
-   echo "Please enter MEL installation path (option -i):"
-   read MELDIR
-   MELDIR="$(abspath ${MELDIR})"
-   if [ ! -d "${MELDIR}" ]; then
-      echo -en "\nERROR (option -i):  Invalid MEL installation path!!!\n\n"
-   fi
-done
+MELDIR="${BUILDDIR%%/build}"
 
-# Construct BUILDDIR from BUILDERR
-if [ -z ${BUILDDIR} ]; then
-   BUILDDIR="${BUILDERR%%/tmp/*}"
-fi
 
 # Clean up artifacts from previous run of the script
 if [ -d "${OUTPUTDIRNAME}" ]; then
