reloc-tests, greedy: set -u, better output of set -e exits
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/greedy-deps-tests b/scripts/greedy-deps-tests
--- a/scripts/greedy-deps-tests
+++ b/scripts/greedy-deps-tests
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash
 #
 # This script tests for greedy configure scripts in recipe builds, which link
 # against things based on their existence in the sysroot.
@@ -6,12 +6,15 @@
 # It does so by building the specified target, then rebuilding all of its
 # dependencies from scratch, one by one, monitoring for buildhistory changes.
 
+set -eu
 
-set -u
+# Emit a useful diagnostic if something fails:
+on_error() {
+    echo >&2 "Error: exited with $? from ${BASH_SOURCE[0]##*/}:${BASH_LINENO[0]}:$BASH_COMMAND"
+}
+trap on_error ERR
 
 cleanup=
-trap handle_sigint INT PIPE
-
 handle_sigint () {
     if  [[ -n $cleanup ]]; then
         eval "$cleanup"
@@ -19,6 +22,7 @@ handle_sigint () {
     trap - 2
     kill -2 $$
 }
+trap handle_sigint INT PIPE
 
 abspath () {
     local path=$1
diff --git a/scripts/reloc-tests b/scripts/reloc-tests
--- a/scripts/reloc-tests
+++ b/scripts/reloc-tests
@@ -5,11 +5,15 @@
 # filesystem, to catch relocation problems.
 
 
-set -e
+set -eu
+
+# Emit a useful diagnostic if something fails:
+on_error() {
+    echo >&2 "Error: exited with $? from ${BASH_SOURCE[0]##*/}:${BASH_LINENO[0]}:$BASH_COMMAND"
+}
+trap on_error ERR
 
 cleanup=
-trap handle_sigint INT PIPE
-
 handle_sigint () {
     if  [[ -n $cleanup ]]; then
         eval "$cleanup"
@@ -17,6 +21,7 @@ handle_sigint () {
     trap - 2
     kill -2 $$
 }
+trap handle_sigint INT PIPE
 
 abspath () {
     local path=$1
@@ -68,6 +73,7 @@ msg_run () {
     return $ret
 }
 
+intr=0
 log_run () {
     local logfile="$1"
     shift
