setup-ubuntu: install virtualenv for toaster setup
We want to use a virtualenv rather than installing into $PYTHONUSERBASE for
our toaster dependencies, so ensure that we have it available. This first
attempts to use apt-get, then falls back to installing virtualenv into
$PYTHONUSERBASE, as the python-virtualenv package is in 'universe' in the
package feeds, which won't be enabled on all systems, and I don't want to try
to script enabling it, even if we wanted to do so.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/setup-ubuntu b/scripts/setup-ubuntu
--- a/scripts/setup-ubuntu
+++ b/scripts/setup-ubuntu
@@ -30,6 +30,33 @@ echo "Installing packages required to build Mentor Embedded Linux"
 sudo apt-get update
 sudo apt-get -y install $PKGS
 
+PYTHONUSERBASE="${PYTHONUSERBASE:-$(python -c 'import site; print(site.USER_BASE)')}"
+PATH="$PYTHONUSERBASE/bin:$PATH"
+if ! which pip >/dev/null 2>&1; then
+    if ! sudo apt-get -y install python-pip 2>/dev/null; then
+        # Install pip & deps into PYTHONUSERBASE if we can't via apt
+        if which curl >/dev/null 2>&1; then
+            curl https://bootstrap.pypa.io/get-pip.py | python - --user
+        else
+            wget -O- https://bootstrap.pypa.io/get-pip.py | python - --user
+        fi
+    fi
+    if ! which pip >/dev/null 2>&1; then
+        echo >&2 "Error: after installing pip, we are not able to execute it"
+        exit 2
+    fi
+fi
+
+if ! which virtualenv >/dev/null 2>&1; then
+    if ! sudo apt-get -y install python-virtualenv 2>/dev/null; then
+        pip install --user virtualenv
+    fi
+    if ! which virtualenv >/dev/null 2>&1; then
+        echo >&2 "Error: after installing virtualenv, we are not able to execute it"
+        exit 2
+    fi
+fi
+
 echo "Generating the en_US.UTF-8 locale"
 locale-gen en_US.UTF-8
 
