setup-mel-builddir: error if we don't find oe-init-build-env
Also return non-zero if bitbake isn't in PATH.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/setup-mel-builddir b/scripts/setup-mel-builddir
--- a/scripts/setup-mel-builddir
+++ b/scripts/setup-mel-builddir
@@ -388,15 +388,17 @@ else
     BUILDDIR="\$(pwd)"
 fi
 export TEMPLATECONF="$TEMPLATECONF"
-for i in $OEROOT/*-init-build-env; do
-    if [ -e "\$i" ]; then
-        . \$i "\$BUILDDIR" "$BITBAKEDIR"
-        break
-    fi
-done
-export BB_ENV_EXTRAWHITE="\$BB_ENV_EXTRAWHITE GIT_SSL_CAINFO MGLS_LICENSE_FILE LM_LICENSE_FILE"
-unset TEMPLATECONF
-cd "\$BUILDDIR"
+OEINIT="\$(find "$OEROOT" -maxdepth 1 -name \*-init-build-env | head -n 1)"
+if [ -z "\$OEINIT" ]; then
+    echo >&2 "oe-init-build-env not found in $OEROOT"
+    false
+else
+    . "\$OEINIT" "\$BUILDDIR" "$BITBAKEDIR"
+    export BB_ENV_EXTRAWHITE="\$BB_ENV_EXTRAWHITE GIT_SSL_CAINFO MGLS_LICENSE_FILE LM_LICENSE_FILE"
+    unset TEMPLATECONF OEINIT
+    cd "\$BUILDDIR"
+    command -v bitbake >/dev/null 2>&1
+fi
 END
 }
 
