Pull back setup script improvements from master
    setup-environment: unbork machine check
    setup-environment: kill debug message
    setup-builddir: handle input other than y/n in the reconfig prompt
    setup-environment: escape $PATH in the generated setup-environment
    setup-environment: dedup the PATH to clean it up
    setup-builddir: don't prompt if reconfiguring for the same machine
    setup-builddir: fix local.conf path
    setup-environment: when no machine is specified, list the ones we can find

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/setup-builddir b/scripts/setup-builddir
--- a/scripts/setup-builddir
+++ b/scripts/setup-builddir
@@ -77,17 +77,24 @@ prioritized_layers () {
 
 # We'll be reconfiguring the build directory, so let the user back out
 if [ -n "$MACHINE" ] &&
-   [ -e $BUILDDIR/conf/bblayers.conf -o -e $BUILDDIR/conf/layer.conf ]; then
+   [ -e $BUILDDIR/conf/bblayers.conf -o -e $BUILDDIR/conf/layer.conf ] &&
+   [ "$MACHINE" != "$(sed -n '/^MACHINE /s/.*"\(.*\)"/\1/p' $BUILDDIR/conf/local.conf 2>/dev/null)" ]; then
     echo >&2 "Build directory is configured, but machine was specified."
-    read -p "Reconfigure for $MACHINE (y|n)? " -n 1 reconfigure
-    echo
-
-    case $reconfigure in
-        [nN])
-            echo >&2 "Aborting at user request"
-            exit 2
-            ;;
-    esac
+    while true; do
+        read -p "Reconfigure for $MACHINE (Y|n)? " reconfigure
+        case $reconfigure in
+            [nN])
+                echo >&2 "Aborting at user request"
+                exit 2
+                ;;
+            ""|[yY])
+                break
+                ;;
+            *)
+                echo >&2 "Invalid input: $reconfigure"
+                ;;
+        esac
+    done
 fi
 
 mkdir -p $BUILDDIR/conf
diff --git a/setup-environment b/setup-environment
--- a/setup-environment
+++ b/setup-environment
@@ -53,6 +53,18 @@ mel_prompt_machine () {
     unset machine_count
 }
 
+mel_list_all_machines () {
+    for layerconf in $MELDIR/*/conf/layer.conf $MELDIR/*/*/conf/layer.conf; do
+        if [ -e "$layerconf" ]; then
+            for machineconf in $(dirname $layerconf)/machine/*.conf; do
+                if [ -e "$machineconf" ]; then
+                    echo $machineconf | sed 's,.*/,,; s,\.conf$,,'
+                fi
+            done
+        fi
+    done
+}
+
 mel_abspath () {
     readlink -f "$1"
 }
@@ -89,7 +101,7 @@ mel_setup () {
             BUILDDIR=$PWD/build
         fi
     fi
-    echo "Creating/configuring build directory $BUILDDIR"
+    echo "Creating/configuring build directory $BUILDDIR.."
 
     if [ $force_overwrite -eq 1 ]; then
         rm -f $BUILDDIR/conf/local.conf $BUILDDIR/conf/bblayers.conf
@@ -106,6 +118,21 @@ mel_setup () {
             # User specified machine and we have the binary content for this BSP
             TEMPLATECONF=$MELDIR/$MACHINE/conf $layerdir/scripts/setup-builddir $BUILDDIR || return 1
         else
+            mel_found=0
+            for layerconf in $MELDIR/*/conf/layer.conf $MELDIR/*/*/conf/layer.conf; do
+                if [ -e "$layerconf" ]; then
+                    if [ -e $(dirname $(dirname $layerconf))/conf/machine/$MACHINE.conf ]; then
+                        mel_found=1
+                        break
+                    fi
+                fi
+            done
+            if [ "$mel_found" -eq 0 ]; then
+                echo >&2 "Error: machine $MACHINE does not exist"
+                return 2
+            fi
+            unset mel_found
+
             # User specified machine, without the binary content -- search
             TEMPLATECONF=$layerdir/conf $layerdir/scripts/setup-builddir $BUILDDIR $MACHINE || return 1
         fi
@@ -122,7 +149,15 @@ mel_setup () {
                 else
                     echo >&2 "Error: no installed bsp, must specify MACHINE"
                     echo >&2
-                    mel_usage
+                    echo >&2 "The following machines are available in your layers:"
+                    echo >&2
+                    mel_list_all_machines | sort | {
+                        if which fmt >/dev/null 2>&1; then
+                            fmt
+                        else
+                            sed 's,^,  ,'
+                        fi
+                    }
                     return 1
                 fi
             fi
@@ -130,7 +165,8 @@ mel_setup () {
         fi
     fi
     PATH="$layerdir/scripts:$MELDIR/poky/scripts:$MELDIR/poky/bitbake/bin:$PATH"
-    echo "PATH=\"$layerdir/scripts:$MELDIR/poky/scripts:$MELDIR/poky/bitbake/bin:$PATH\"; cd $BUILDDIR" > $BUILDDIR/setup-environment
+    PATH="$(printf "$PATH" | awk -v RS=: -v ORS=: '!arr[$0]++' | sed 's/::/:/g; s/:$//; s/^://')"
+    echo "PATH=\"$layerdir/scripts:$MELDIR/poky/scripts:$MELDIR/poky/bitbake/bin:\$PATH\"; cd $BUILDDIR" > $BUILDDIR/setup-environment
 
     cd $BUILDDIR
 
@@ -160,6 +196,9 @@ if [ -z "$ZSH_NAME" ] && [ "${0##*/}" = "setup-environment" ]; then
 else
     if [ -n "$ZSH_NAME" ]; then
         layerdir=${0%/*}
+
+        # Don't error if a glob fails to match anything
+        set -3
     elif [ -n "$BASH_SOURCE" ]; then
         layerdir=${BASH_SOURCE%/*}
     else
@@ -171,5 +210,5 @@ else
     layerdir=$(mel_abspath $layerdir)
     mel_setup "$@"
     unset layerdir
-    unset -f mel_setup mel_usage mel_prompt_machine mel_abspath
+    unset -f mel_setup mel_usage mel_prompt_machine mel_list_all_machines mel_abspath
 fi
