setup-builddir: prompt for reconfiguration as appropriate
If the user specifies a machine, then they likely want the build directory
configured for that machine, but we want to be sure of this, so if the build
dir exists already and is configured, and machine is specified, then prompt to
continue and reconfigure it.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/setup-builddir b/scripts/setup-builddir
--- a/scripts/setup-builddir
+++ b/scripts/setup-builddir
@@ -76,6 +76,21 @@ prioritized_layers () {
     done | sort -n -k2 -r | cut -d" " -f1 | sed "s,$OEDIR/,\${OEDIR}/,; s,$PWD,\${TOPDIR}/..,"
 }
 
+# We'll be reconfiguring the build directory, so let the user back out
+if [ -n "$MACHINE" ] &&
+   [ -e $BUILDDIR/conf/bblayers.conf -o -e $BUILDDIR/conf/layer.conf ]; then
+    echo >&2 "Build directory is configured, but machine was specified."
+    read -p "Reconfigure for $MACHINE (y|n)? " -n 1 reconfigure
+    echo
+
+    case $reconfigure in
+        [nN])
+            echo >&2 "Aborting at user request"
+            exit 2
+            ;;
+    esac
+fi
+
 mkdir -p $BUILDDIR/conf
 if [ ! -e $BUILDDIR/conf/local.conf ]; then
     cp $TEMPLATECONF/local.conf.sample $BUILDDIR/conf/local.conf
