setup-mel-builddir: mention MACHINE in the cannot prompt message
"please specify" is vague and implies that the user needs to specify the BSP,
which is not correct, as it's the MACHINE that needs to be specified.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/setup-mel-builddir b/scripts/setup-mel-builddir
--- a/scripts/setup-mel-builddir
+++ b/scripts/setup-mel-builddir
@@ -261,7 +261,7 @@ setup_builddir () {
                     fi
                     echo "$machine"
                 done | prompt_choice $non_interactive "Select BSP to use" >$tmpfile || {
-                echo >&2 "Error: unable to prompt for an installed MEL BSP, please specify"
+                echo >&2 "Error: unable to prompt for an installed MEL BSP, please specify MACHINE"
                 return 1
             }
             MACHINE="$(cat "$tmpfile")"
