wrap: don't set BUILDDIR if it's already set in the environment
This way the user can override the automatic behavior if they choose to.

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/scripts/wrap b/scripts/wrap
--- a/scripts/wrap
+++ b/scripts/wrap
@@ -15,10 +15,12 @@ wrap() {
     wrapperdir=$(cd ${1%/*} && pwd)
     shift
 
-    export BUILDDIR=$(find_builddir)
     if [ -z "$BUILDDIR" ]; then
-        echo >&2 "Error: must run $cmd from under your build directory"
-        exit 1
+        export BUILDDIR=$(find_builddir)
+        if [ -z "$BUILDDIR" ]; then
+            echo >&2 "Error: must run $cmd from under your build directory"
+            exit 1
+        fi
     fi
     cd $BUILDDIR
 
